baseURL = "http://noah-pitts.github.io/"
title = "Noah Pitts"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 6
enableEmoji = true

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup.highlight]
noClasses = false

[params]
author = "Noah Pitts"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Noah Pitts's personal website"
keywords = "blog,developer,personal"
info = ["Hello/ Hola/ Bonjour/ Namaste/ Hallo ğŸ‘‹ğŸ¾","I Love Data <3"]
#avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2024
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/noah-pitts/"


[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/noah-pitts/"

[[params.social]]
name = "Medium"
icon = "fa-brands fa-medium fa-2x"
weight = 5
url = "https://medium.com/@noah.pitts713"


[languages.en]
languageName = "EN"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[languages.es]
languageName = "ESP"
title = "Noah Pitts"

[languages.es.params]
author = "Noah Pitts"
info = ["Hello/ Hola/ Bonjour/ Namaste/ Hallo ğŸ‘‹ğŸ¾","Me encantan los datos <3"]
description = "Sitio personal de Noah Pitts"
keywords = "blog,desenvolvedor,pessoal"

[[languages.es.menu.main]]
name = "Sobre"
weight = 1
url = "about/"

[[languages.es.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.es.menu.main]]
name = "Proyectos"
weight = 3
url = "projects/"

[[languages.es.menu.main]]
name = "Contacto"
weight = 5
url = "contact/"
